package permissions.db.repos;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import permissions.db.PagingInfo;
import permissions.db.PersonRepository;
import permissions.db.mapper.PersonMapper;
import permissions.domain.Person;

public class HsqlPersonRepository implements PersonRepository {

    private Connection connection;

    private PersonMapper personMapper;

    private String selectBySurnameSql = "SELECT * FROM person WHERE Surname=? OFFSET ? LIMIT ?";
    private String selectByNameSql = "SELECT * FROM person WHERE Name=? OFFSET ? LImit ?";

    private PreparedStatement selectBySurname;
    private PreparedStatement selectByName;
    private PreparedStatement delete;

    private String createPersonTable = ""
        + "CREATE TABLE Person("
        + "id bigint GENERATED BY DEFAULT AS IDENTITY,"
        + "name VARCHAR(20),"
        + "surname VARCHAR(50)"
        + ")";

    public HsqlPersonRepository(Connection connection) {
        this.connection = connection;

        this.personMapper = new PersonMapper(connection);

        try {

            ResultSet rs = connection.getMetaData().getTables(null, null, null, null);

            boolean tableExists = false;
            while (rs.next()) {
                if (rs.getString("TABLE_NAME").equalsIgnoreCase("Person")) {
                    tableExists = true;
                    break;
                }
            }
            if (!tableExists) {
                Statement createTable = connection.createStatement();
                createTable.executeUpdate(createPersonTable);
            }

            selectByName = connection.prepareStatement(selectByNameSql);
            selectBySurname = connection.prepareStatement(selectBySurnameSql);

        } catch (SQLException ex) {
            ex.printStackTrace();
        }

    }

    @Override
    public Person withId(int id) {
        return personMapper.find((long) id);
    }

    public List<Person> allOnPage(PagingInfo page) {
        return personMapper.findAllOnPage(page);
    }

    public void add(Person person) {
        personMapper.add(person);

    }

    public void modify(Person p) {
        personMapper.update(p);
    }

    public void remove(Person p) {
        personMapper.remove((long) p.getId());
    }

    public List<Person> withSurname(String surname, PagingInfo page) {

        List<Person> result = new ArrayList<Person>();
        try {
            selectBySurname.setString(1, surname);
            selectBySurname.setInt(2, page.getCurrentPage() * page.getSize());
            selectBySurname.setInt(3, page.getSize());
            ResultSet rs = selectBySurname.executeQuery();
            while (rs.next()) {
                Person person = new Person();
                person.setName(rs.getString("name"));
                person.setSurname(rs.getString("surname"));
                person.setId(rs.getInt("id"));
                result.add(person);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return result;
    }

    public List<Person> withName(String name, PagingInfo page) {

        List<Person> result = new ArrayList<Person>();
        try {
            selectByName.setString(1, name);
            selectByName.setInt(2, page.getCurrentPage() * page.getSize());
            selectByName.setInt(3, page.getSize());
            ResultSet rs = selectByName.executeQuery();
            while (rs.next()) {
                Person person = new Person();
                person.setName(rs.getString("name"));
                person.setSurname(rs.getString("surname"));
                person.setId(rs.getInt("id"));
                result.add(person);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return result;
    }

}
